# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9cd7bae5bf8c9a1b6cc7127d7886750958964b49d224cb5c9d2889caeb3b26a84e8f48146e0e2fc1f70dc3084f9821dac5b7e3e33031af668e35b5f85d5434f6

test:
  secret_key_base: 02e527c0c6fc15baca83c3a5ead3bc84fbcaf65d9eeca9d2c7a1a7495bfed514e6af3b724f625e90621b2faf1ccd8fa3ec5b0ce7b3a97aabd941b54156f43e5e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
